export const packages = [
  {
    id: "website",
    name: "Healthcare website",
    unit: "one-time",
    note: "Good for a new practice, clinic or health service that needs a clear digital front door.",
    tiers: [
      {
        name: "Essentials",
        price: "₹30k–₹45k",
        timeline: "2–3 weeks",
        features: [
          "Up to 5 responsive pages",
          "Services and practitioner information",
          "Contact and enquiry pathway",
          "Foundational on-page SEO",
          "Launch and handover",
        ],
      },
      {
        name: "Practice Growth",
        price: "₹60k–₹1L",
        timeline: "3–5 weeks",
        features: [
          "Up to 12 custom pages",
          "Multiple services or practitioners",
          "CMS for routine content updates",
          "Analytics and enquiry tracking",
          "SEO-ready page structure",
        ],
      },
      {
        name: "Multi-service",
        price: "₹1L–₹2.5L+",
        timeline: "Scoped to content",
        features: [
          "Custom structure for departments or locations",
          "Expanded service and patient information",
          "Advanced enquiry or booking pathways",
          "Content migration and structured data",
          "Accessibility and performance review",
        ],
      },
    ],
  },
  {
    id: "patient",
    name: "Patient experience or portal",
    unit: "one-time",
    note: "For teams improving the digital steps patients take before, during or after care.",
    tiers: [
      {
        name: "Journey Starter",
        price: "₹75k–₹1.5L",
        timeline: "3–5 weeks",
        features: [
          "Patient journey mapping",
          "Responsive patient-facing interface",
          "Clear service and next-step information",
          "Clickable prototype",
          "Usability review",
        ],
      },
      {
        name: "Patient Portal",
        price: "₹1.5L–₹3L",
        timeline: "6–10 weeks",
        features: [
          "Patient sign-in and account views",
          "Appointments and visit information",
          "Role-aware interface states",
          "Admin content and task views",
          "Release and handover plan",
        ],
      },
      {
        name: "Connected Experience",
        price: "₹3L+",
        timeline: "Phased delivery",
        features: [
          "Multiple patient journeys or user roles",
          "Integration planning with existing tools",
          "Notifications and follow-up flows",
          "Operational reporting views",
          "Phased roadmap and support",
        ],
      },
    ],
  },
  {
    id: "appointments",
    name: "Appointment system",
    unit: "one-time",
    note: "Final scope depends on booking rules, provider schedules, reminders and system connections.",
    tiers: [
      {
        name: "Booking Basics",
        price: "₹75k–₹1.5L",
        timeline: "4–6 weeks",
        features: [
          "Service and provider selection",
          "Available time-slot flow",
          "Booking confirmation screen",
          "Staff schedule overview",
          "Responsive web experience",
        ],
      },
      {
        name: "Practice Booking",
        price: "₹1.5L–₹3L",
        timeline: "6–10 weeks",
        features: [
          "Multiple providers or locations",
          "Rescheduling and cancellation flows",
          "Staff calendar and admin views",
          "Email or SMS reminder planning",
          "Booking activity summaries",
        ],
      },
      {
        name: "Connected Scheduling",
        price: "₹3L+",
        timeline: "Phased delivery",
        features: [
          "Complex scheduling rules",
          "Role-based staff workflows",
          "Integration assessment and build",
          "Operational reporting",
          "Rollout and monitoring plan",
        ],
      },
    ],
  },
  {
    id: "ehr",
    name: "EHR software",
    unit: "one-time",
    note: "A focused workflow or prototype costs less than a production system with multiple roles and integrations.",
    tiers: [
      {
        name: "Workflow Prototype",
        price: "₹1.5L–₹3L",
        timeline: "4–8 weeks",
        features: [
          "Clinical workflow discovery",
          "Patient and visit record interface",
          "Key role and access patterns",
          "Interactive prototype or focused release",
          "Technical delivery plan",
        ],
      },
      {
        name: "Core Records",
        price: "₹3L–₹7L",
        timeline: "8–16 weeks",
        features: [
          "Patient profile and visit history",
          "Structured record-entry workflows",
          "Role-aware staff screens",
          "Search and record summaries",
          "Documentation and handover",
        ],
      },
      {
        name: "Extended Platform",
        price: "₹7L+",
        timeline: "Phased delivery",
        features: [
          "Multiple clinical workflows",
          "Integration and migration planning",
          "Expanded roles and permissions",
          "Operational views and reporting",
          "Phased roadmap and release support",
        ],
      },
    ],
  },
  {
    id: "clinic",
    name: "Clinic management",
    unit: "one-time",
    note: "Modules, provider roles, locations, reporting and migration needs shape the final scope.",
    tiers: [
      {
        name: "Clinic Essentials",
        price: "₹1.5L–₹3L",
        timeline: "6–10 weeks",
        features: [
          "Patient and provider records",
          "Appointment overview",
          "Daily staff task views",
          "Role-aware access patterns",
          "Responsive staff dashboard",
        ],
      },
      {
        name: "Practice Operations",
        price: "₹3L–₹8L",
        timeline: "10–16 weeks",
        features: [
          "Multi-provider workflows",
          "Follow-up and task coordination",
          "Operational summaries and reports",
          "Configurable clinic settings",
          "Training and handover materials",
        ],
      },
      {
        name: "Multi-location",
        price: "₹8L+",
        timeline: "Phased delivery",
        features: [
          "Multiple locations and teams",
          "Cross-location operational views",
          "Integration and data migration planning",
          "Expanded permissions and workflows",
          "Phased rollout and support",
        ],
      },
    ],
  },
  {
    id: "hospital",
    name: "Hospital management",
    unit: "one-time",
    note: "Larger systems are scoped in phases around priority departments and agreed workflows.",
    tiers: [
      {
        name: "Workflow Release",
        price: "₹3L–₹6L",
        timeline: "8–12 weeks",
        features: [
          "Discovery for one priority workflow",
          "Internal dashboard or portal",
          "Role and handoff mapping",
          "Focused first release",
          "Technical rollout plan",
        ],
      },
      {
        name: "Department Suite",
        price: "₹6L–₹15L",
        timeline: "Phased delivery",
        features: [
          "Workflows across agreed teams",
          "Operational dashboard views",
          "Role-based tasks and information",
          "Integration assessment",
          "Documentation and team handover",
        ],
      },
      {
        name: "Hospital Platform",
        price: "₹15L+",
        timeline: "Roadmap-led",
        features: [
          "Multiple departments and workflows",
          "System integration planning",
          "Phased data and service rollout",
          "Operational reporting foundation",
          "Ongoing improvement partnership",
        ],
      },
    ],
  },
  {
    id: "content",
    name: "Healthcare content creation",
    unit: "one-time",
    note: "Prices depend on page volume, interviews and the clinical review process required.",
    tiers: [
      {
        name: "Core Pages",
        price: "₹15k–₹30k",
        timeline: "1–2 weeks",
        features: [
          "Copy for up to 3 key pages",
          "Patient-friendly language",
          "One review round",
          "Basic search structure",
          "Final web-ready copy",
        ],
      },
      {
        name: "Website Content",
        price: "₹30k–₹60k",
        timeline: "2–4 weeks",
        features: [
          "Copy for up to 8 pages",
          "Practitioner and service content",
          "Content interview or briefing",
          "Two review rounds",
          "Page titles and meta descriptions",
        ],
      },
      {
        name: "Content Programme",
        price: "₹60k+",
        timeline: "Scoped to volume",
        features: [
          "Expanded page or article set",
          "Editorial themes and content plan",
          "Subject-matter review workflow",
          "Reusable voice and style guidance",
          "Publishing-ready handover",
        ],
      },
    ],
  },
  {
    id: "seo",
    name: "Healthcare SEO",
    unit: "per month",
    note: "SEO is an ongoing effort; scope and progress are reviewed regularly rather than guaranteed by a fixed date.",
    tiers: [
      {
        name: "Local Foundations",
        price: "₹12k–₹20k",
        timeline: "Monthly",
        features: [
          "Local search profile review",
          "Priority page recommendations",
          "On-page title and heading updates",
          "Monthly action summary",
          "One location focus",
        ],
      },
      {
        name: "Search Growth",
        price: "₹20k–₹35k",
        timeline: "Monthly",
        features: [
          "Local and technical review",
          "Service-page improvements",
          "Internal linking and content plan",
          "Search performance review",
          "Monthly priority recommendations",
        ],
      },
      {
        name: "Multi-location SEO",
        price: "₹35k+",
        timeline: "Monthly",
        features: [
          "Multiple location pages",
          "Expanded technical and content work",
          "Structured reporting and review",
          "Cross-location search planning",
          "Ongoing optimisation backlog",
        ],
      },
    ],
  },
  {
    id: "integrations",
    name: "Healthcare integrations",
    unit: "one-time",
    note: "Effort depends on API access, vendor constraints, data formats and monitoring requirements.",
    tiers: [
      {
        name: "Single Connection",
        price: "₹50k–₹1.5L",
        timeline: "3–6 weeks",
        features: [
          "Integration discovery",
          "One system connection",
          "Field mapping and validation",
          "Error-handling plan",
          "Technical notes and handover",
        ],
      },
      {
        name: "Connected Workflow",
        price: "₹1.5L–₹4L",
        timeline: "6–10 weeks",
        features: [
          "Multiple data handoffs",
          "Workflow and field mapping",
          "Monitoring and error review",
          "Test and rollout plan",
          "Integration documentation",
        ],
      },
      {
        name: "Integration Suite",
        price: "₹4L+",
        timeline: "Phased delivery",
        features: [
          "Multiple systems or workflows",
          "Expanded monitoring and recovery",
          "Migration or transformation planning",
          "Security and access review",
          "Phased release support",
        ],
      },
    ],
  },
  {
    id: "support",
    name: "Ongoing support",
    unit: "per month",
    note: "Monthly support is tailored to update cadence, response expectations and improvement goals.",
    tiers: [
      {
        name: "Care",
        price: "₹5k–₹10k",
        timeline: "Monthly",
        features: [
          "Routine updates",
          "Backup and uptime checks",
          "Small content or bug fixes",
          "Email support",
          "Monthly status note",
        ],
      },
      {
        name: "Care + Improve",
        price: "₹10k–₹20k",
        timeline: "Monthly",
        features: [
          "Everything in Care",
          "Planned improvement time",
          "Performance and accessibility checks",
          "Priority issue handling",
          "Monthly planning call",
        ],
      },
      {
        name: "Product Partner",
        price: "₹20k+",
        timeline: "Monthly",
        features: [
          "Ongoing technical partnership",
          "Larger improvement capacity",
          "Release planning and review",
          "Team coordination",
          "Roadmap recommendations",
        ],
      },
    ],
  },
];
